const $=s=>document.querySelector(s),canvas=$("#game"),ctx=canvas.getContext("2d"),scoreEl=$("#score"),bestEl=$("#best"),ballsEl=$("#balls"),soundBtn=$("#sound"),exitBtn=$("#exit"),launchBtn=$("#launch"),leftBtn=$("#left"),rightBtn=$("#right"),message=$("#message"),gameover=$("#gameover");
const progress=document.createElement("span");progress.innerHTML='・點亮 <span id="lit">0</span>/7';ballsEl.parentElement.append(progress);const litEl=$("#lit");
const W=700,H=1100,KEY="glitch-park-pinball:v1",THEME="./assets/audio/glitch-park-theme.mp3",embedded=self!==top;const names=["格莉奇","貓草","斑比","諾亞","鐵塔","0x","黑洞先生"],colors=["#9e8ce0","#75b78b","#df91ad","#ce9860","#6c9bc3","#7c8292","#554b62"];
if(embedded){const brand=exitBtn.closest(".brand"),topLeft=document.createElement("div"),style=document.createElement("style");document.documentElement.classList.add("embedded");topLeft.className="topLeft";brand.before(topLeft);topLeft.append(exitBtn,brand);style.textContent=".topLeft{display:flex;align-items:flex-start;gap:8px}.embedded .tools{margin-right:64px}@media(max-width:620px){.embedded .tools{margin-top:54px;margin-right:0}}";document.head.append(style)}
let localStore=false,savedState={best:0,lit:[]};try{localStorage.setItem(KEY+":probe","1");localStorage.removeItem(KEY+":probe");localStore=true;const raw=localStorage.getItem(KEY);if(raw){try{const parsed=JSON.parse(raw);savedState=typeof parsed==="number"?{best:parsed,lit:[]}:{...savedState,...parsed}}catch{savedState.best=Number(raw)||0}}}catch{}
let best=Number(savedState.best)||0,lit=new Set(Array.isArray(savedState.lit)?savedState.lit:[]);
let score=0,balls=3,sound=true,audioContext,themeAudio,last=performance.now(),scale=1,ox=0,oy=0,messageTimer=0,leftHeld=false,rightHeld=false,started=false,gameEnded=false,inShooterLane=false,plungerDragging=false,plungerStartY=0,plungerPull=0,plungerHoldStart=0,plungerDragPull=0,keyPlungerStart=0,shake=0,neonEnergy=0,powerCooldown=0;
const atlas=new Image();atlas.src="./assets/avatar-atlas.webp";atlas.onload=draw;
const SHOOTER_X=607,SHOOTER_REST_Y=962,SHOOTER_PULL_DISTANCE=30;
function makeBall(x=SHOOTER_X,y=SHOOTER_REST_Y,vx=0,vy=0){return{x,y,vx,vy,r:13,active:false,effectTime:0,trail:[],soundWait:0}}
// 最上排三位角色要留出真正能落球的通道，不能讓三個大圓彼此形成長時間彈跳籠。
const ball=makeBall(),playBalls=[ball],particles=[],bumpers=[
  // 中央最大兩顆固定給主角格莉奇與黑洞先生；斑比、諾亞移到上排，七人仍各出現一次。
  {x:210,y:300,r:47,i:2,flash:0},{x:350,y:235,r:47,i:3,flash:0},{x:490,y:300,r:47,i:1,flash:0},
  {x:280,y:445,r:52,i:0,flash:0},{x:420,y:445,r:52,i:6,flash:0},
  {x:270,y:590,r:42,i:4,flash:0},{x:430,y:590,r:42,i:5,flash:0}
];
const FLIPPER_LEFT_X=250,FLIPPER_RIGHT_X=450,FLIPPER_Y=865,FLIPPER_LENGTH=70;
function requestTheme(action,muted=false){if(embedded){parent.postMessage({type:"glitch-park:music",action,track:"theme",url:new URL(THEME,location.href).href,muted},"*");return}themeAudio||=Object.assign(new Audio(THEME),{loop:true,volume:.25});themeAudio.muted=muted;if(action==="play"&&!muted)themeAudio.play().catch(()=>{});if(action==="pause")themeAudio.pause()}
if(embedded){
  exitBtn.hidden=false;exitBtn.onclick=()=>parent.postMessage({type:"pinball:exit",complete:lit.size===names.length},"*");
  addEventListener("message",event=>{if(event.data?.type!=="pinball:state")return;const state=event.data.state||{};best=Math.max(best,Number(state.best)||0);lit=new Set([...(Array.isArray(state.lit)?state.lit:[]),...lit]);paintProgress();draw()});
  parent.postMessage({type:"pinball:ready"},"*");
}else requestTheme("play");
function saveState(){const state={best,lit:[...lit]};if(localStore){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}}else if(embedded)parent.postMessage({type:"pinball:save",state},"*")}
function beep(freq,dur=.08,vol=.05,type="sine"){if(!sound)return;audioContext||=new(window.AudioContext||window.webkitAudioContext)();const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+dur);o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+dur)}
function sfxImpact(i){beep(510+i*42,.075,.055,"triangle");setTimeout(()=>beep(860+i*28,.035,.026,"square"),28)}
function sfxLaunch(power){beep(115,.24,.07,"sawtooth");setTimeout(()=>beep(320+power*180,.12,.05,"triangle"),90)}
function sfxPower(){[620,830,1040].forEach((f,i)=>setTimeout(()=>beep(f,.14,.055,"triangle"),i*65))}
function sfxDrain(){beep(130,.3,.06,"sawtooth");setTimeout(()=>beep(82,.28,.045,"triangle"),105)}
soundBtn.onclick=()=>{sound=!sound;soundBtn.textContent=`聲音：${sound?"開":"關"}`;soundBtn.setAttribute("aria-pressed",String(!sound));requestTheme("mute",!sound);if(sound){requestTheme("play");beep(660)}};
function resize(){const dpr=Math.min(devicePixelRatio,1.7);canvas.width=innerWidth*dpr;canvas.height=innerHeight*dpr;canvas.style.width=innerWidth+"px";canvas.style.height=innerHeight+"px";scale=Math.min(innerWidth/W,innerHeight/H);ox=(innerWidth-W*scale)/2;oy=(innerHeight-H*scale)/2;ctx.setTransform(dpr,0,0,dpr,0,0);draw()}addEventListener("resize",resize);resize();
function tableTransform(){const dpr=Math.min(devicePixelRatio,1.7),jx=shake?Math.sin(performance.now()*.11)*shake:0,jy=shake?Math.cos(performance.now()*.135)*shake*.55:0;ctx.setTransform(dpr*scale,0,0,dpr*scale,dpr*(ox+jx*scale),dpr*(oy+jy*scale))}
function drawRoom(){const time=performance.now()*.001,horizon=innerHeight*.73,bg=ctx.createRadialGradient(innerWidth/2,innerHeight*.42,20,innerWidth/2,innerHeight*.45,Math.max(innerWidth,innerHeight));bg.addColorStop(0,neonEnergy>.15?"#76548d":"#674879");bg.addColorStop(.55,"#432e57");bg.addColorStop(1,"#1c1129");ctx.fillStyle=bg;ctx.fillRect(0,0,innerWidth,innerHeight);ctx.fillStyle="rgba(9,4,17,.15)";for(let i=0;i<9;i++)ctx.fillRect(i*innerWidth/8-2,0,4,horizon);ctx.strokeStyle="rgba(255,173,220,.22)";ctx.lineWidth=1.5;for(let y=82;y<horizon;y+=74){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(innerWidth,y);ctx.stroke()}ctx.strokeStyle="rgba(105,238,224,.3)";ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(innerWidth/2,horizon+30,innerWidth*.47,innerHeight*.58,0,Math.PI,Math.PI*2);ctx.stroke();const floor=ctx.createLinearGradient(0,horizon,0,innerHeight);floor.addColorStop(0,"#49345e");floor.addColorStop(1,"#171022");ctx.fillStyle=floor;ctx.fillRect(0,horizon,innerWidth,innerHeight-horizon);ctx.strokeStyle="rgba(105,238,224,.22)";ctx.lineWidth=1;for(let i=-10;i<=10;i++){ctx.beginPath();ctx.moveTo(innerWidth/2+i*22,horizon);ctx.lineTo(innerWidth/2+i*innerWidth*.13,innerHeight);ctx.stroke()}for(let i=0;i<7;i++){const p=i/7,y=horizon+(innerHeight-horizon)*p*p;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(innerWidth,y);ctx.stroke()}if(innerWidth>900){for(const side of [-1,1]){const x=innerWidth/2+side*Math.min(innerWidth*.4,540),y=horizon-30;ctx.save();ctx.translate(x,y);ctx.shadowBlur=20;ctx.shadowColor=side<0?"#69eee0":"#ff72c5";ctx.strokeStyle=ctx.shadowColor;ctx.fillStyle="#241532";ctx.lineWidth=5;ctx.beginPath();ctx.roundRect(-72,-190,144,285,18);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle="#513568";ctx.fillRect(-58,-170,116,48);ctx.fillStyle="#ffd36e";ctx.font="900 22px system-ui";ctx.textAlign="center";ctx.fillText("GLITCH",0,-139);ctx.fillStyle="#13091e";ctx.fillRect(-54,-104,108,120);for(let i=0;i<3;i++){ctx.fillStyle=i%2?"#ff72c5":"#69eee0";ctx.beginPath();ctx.arc(0,-78+i*40,12,0,Math.PI*2);ctx.fill()}ctx.fillStyle="#604178";ctx.fillRect(-56,30,112,46);ctx.restore()}}}
function drawCabinetDetails(){ctx.save();ctx.strokeStyle="rgba(255,255,255,.18)";ctx.lineWidth=2;roundRect(82,48,536,1004,30);ctx.stroke();for(const [x,y] of [[91,82],[609,82],[91,1015],[609,1015]]){ctx.fillStyle="#d8d1e7";ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#554164";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x-4,y);ctx.lineTo(x+4,y);ctx.stroke()}const marquee=ctx.createLinearGradient(145,0,555,0);marquee.addColorStop(0,"#69eee0");marquee.addColorStop(.5,"#f6f1ff");marquee.addColorStop(1,"#ff72c5");ctx.fillStyle=marquee;ctx.shadowBlur=18;ctx.shadowColor="#69eee0";roundRect(200,89,300,76,14);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#160b24";roundRect(207,96,286,62,10);ctx.fill();ctx.fillStyle="#fff";ctx.textAlign="center";ctx.font="900 39px system-ui";ctx.fillText("GLITCH",350,133);ctx.fillStyle="#ffd36e";ctx.font="700 12px system-ui";ctx.fillText("NEON PINBALL",350,151);ctx.restore()}
function drawGlassSheen(){ctx.save();ctx.globalCompositeOperation="screen";const sheen=ctx.createLinearGradient(115,120,560,900);sheen.addColorStop(0,"rgba(255,255,255,0)");sheen.addColorStop(.42,"rgba(210,249,255,.08)");sheen.addColorStop(.5,"rgba(255,255,255,.14)");sheen.addColorStop(.58,"rgba(210,249,255,.03)");sheen.addColorStop(1,"rgba(255,255,255,0)");ctx.fillStyle=sheen;ctx.beginPath();ctx.moveTo(110,90);ctx.lineTo(285,90);ctx.lineTo(590,995);ctx.lineTo(430,995);ctx.closePath();ctx.fill();ctx.restore()}
function draw(){const dpr=Math.min(devicePixelRatio,1.7);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,innerWidth,innerHeight);drawRoom();tableTransform();ctx.save();ctx.shadowBlur=35+neonEnergy*28;ctx.shadowColor=neonEnergy>.3?"#ff72c5":"#69eee0";roundRect(70,35,560,1030,34);ctx.fillStyle="#171024";ctx.fill();ctx.strokeStyle=neonEnergy>.3?"#ff8fd2":"#69eee0";ctx.lineWidth=8+neonEnergy*2;ctx.stroke();ctx.shadowBlur=0;const panel=ctx.createLinearGradient(0,100,0,1000);panel.addColorStop(0,"#4d2c6c");panel.addColorStop(.52,"#211336");panel.addColorStop(1,"#120a20");roundRect(95,65,510,965,25);ctx.fillStyle=panel;ctx.fill();ctx.strokeStyle="#ff72c5";ctx.lineWidth=3;ctx.stroke();drawCabinetDetails();drawPoster();drawRails();for(const b of bumpers)drawBumper(b);drawTargets();drawFlipper(FLIPPER_LEFT_X,FLIPPER_Y,leftHeld?-.48:.2,FLIPPER_LENGTH,"#69eee0");drawFlipper(FLIPPER_RIGHT_X,FLIPPER_Y,rightHeld?Math.PI+.48:Math.PI-.2,FLIPPER_LENGTH,"#ff72c5");ctx.fillStyle="#08040e";ctx.beginPath();ctx.moveTo(95,1015);ctx.lineTo(250,880);ctx.lineTo(318,1030);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(605,1015);ctx.lineTo(450,880);ctx.lineTo(382,1030);ctx.closePath();ctx.fill();drawShooterCharge();drawEffects();for(const orb of playBalls)if(orb.active)drawBall(orb);if(!playBalls.some(o=>o.active)&&!gameEnded)drawBall(ball);drawGlassSheen();ctx.restore()}
function drawBall(orb){for(let i=0;i<orb.trail.length;i++){const t=orb.trail[i];ctx.globalAlpha=(i+1)/orb.trail.length*.25;ctx.fillStyle=orb.r>14?"#ffd36e":orb.r<12?"#ff72c5":"#69eee0";ctx.beginPath();ctx.arc(t.x,t.y,Math.max(3,orb.r*(i+1)/orb.trail.length*.65),0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.shadowBlur=22;ctx.shadowColor=orb.r>14?"#ffd36e":orb.r<12?"#ff72c5":"#fff";ctx.fillStyle="#f7fbff";ctx.beginPath();ctx.arc(orb.x,orb.y,orb.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#b9d8e0";ctx.beginPath();ctx.arc(orb.x-orb.r*.3,orb.y-orb.r*.38,Math.max(3,orb.r*.28),0,Math.PI*2);ctx.fill()}
function drawEffects(){ctx.save();ctx.globalCompositeOperation="lighter";for(const p of particles){ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size*p.life,0,Math.PI*2);ctx.fill()}ctx.restore();ctx.globalAlpha=1}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function drawPoster(){ctx.save();ctx.globalAlpha=.2;ctx.fillStyle="#9e8ce0";ctx.font="900 54px system-ui";ctx.textAlign="center";ctx.fillText("LUCKY SEVEN",350,205);ctx.restore()}
function drawRails(){ctx.strokeStyle="#9cefe8";ctx.lineWidth=10;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(118,190);ctx.lineTo(118,700);ctx.lineTo(245,842);ctx.stroke();ctx.beginPath();ctx.moveTo(582,190);ctx.lineTo(582,700);ctx.lineTo(455,842);ctx.stroke();ctx.strokeStyle="#ff72c5";ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(118,1010);ctx.lineTo(252,872);ctx.stroke();ctx.beginPath();ctx.moveTo(582,1010);ctx.lineTo(448,872);ctx.stroke();ctx.strokeStyle="#6c3f88";ctx.lineWidth=5;ctx.beginPath();ctx.arc(350,500,205,.15,Math.PI-.15);ctx.stroke();
// 發射道不只是裝飾：雙軌一路從彈簧延伸到頂端，並以彎道接回主檯面。
ctx.strokeStyle="#ffd36e";ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(590,1015);ctx.lineTo(590,190);ctx.quadraticCurveTo(590,115,515,115);ctx.stroke();ctx.beginPath();ctx.moveTo(625,1015);ctx.lineTo(625,190);ctx.quadraticCurveTo(625,82,515,82);ctx.stroke()}
function drawShooterCharge(){const charging=plungerDragging||!!keyPlungerStart,power=charging?plungerPull:0,ballY=charging?SHOOTER_REST_Y+power*SHOOTER_PULL_DISTANCE:ball.y;ctx.save();ctx.strokeStyle="#ffd36e";ctx.lineWidth=3;ctx.shadowBlur=12;ctx.shadowColor="#ffd36e";ctx.beginPath();const springTop=ball.active&&!charging?1004:Math.min(1004,ballY+17),springBottom=1015,turns=6;ctx.moveTo(SHOOTER_X,springTop);for(let i=1;i<=turns;i++){const y=springTop+(springBottom-springTop)*i/turns;ctx.lineTo(SHOOTER_X+(i%2?8:-8),y)}ctx.lineTo(SHOOTER_X,springBottom);ctx.stroke();ctx.shadowBlur=0;roundRect(548,865,25,135,9);ctx.fillStyle="rgba(8,4,14,.72)";ctx.fill();ctx.strokeStyle="rgba(255,211,110,.72)";ctx.lineWidth=2;ctx.stroke();const fill=121*power;if(fill>0){const gauge=ctx.createLinearGradient(0,986,0,865);gauge.addColorStop(0,"#69eee0");gauge.addColorStop(.58,"#ffd36e");gauge.addColorStop(1,"#ff72c5");ctx.fillStyle=gauge;roundRect(553,993-fill,15,fill,5);ctx.fill()}ctx.fillStyle="#fff4ce";ctx.textAlign="center";ctx.font="800 12px system-ui";ctx.fillText("蓄力",560,853);ctx.font="900 13px system-ui";ctx.fillText(`${Math.round(power*100)}%`,560,1020);ctx.restore()}
function drawBumper(b){ctx.save();ctx.shadowBlur=22+b.flash*35;ctx.shadowColor=colors[b.i];ctx.fillStyle="#0b0612";ctx.beginPath();ctx.arc(b.x,b.y,b.r+9+b.flash*4,0,Math.PI*2);ctx.fill();ctx.strokeStyle=colors[b.i];ctx.lineWidth=7;ctx.stroke();ctx.shadowBlur=0;const ring=ctx.createRadialGradient(b.x-b.r*.28,b.y-b.r*.32,2,b.x,b.y,b.r);ring.addColorStop(0,"#fff");ring.addColorStop(.18,colors[b.i]);ring.addColorStop(1,"#271733");ctx.fillStyle=ring;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(b.x,b.y,b.r-11,0,Math.PI*2);ctx.clip();if(atlas.complete&&atlas.naturalWidth){const sw=atlas.naturalWidth/4,sh=atlas.naturalHeight/2;ctx.drawImage(atlas,(b.i%4)*sw,Math.floor(b.i/4)*sh,sw,sh,b.x-b.r+11,b.y-b.r+11,(b.r-11)*2,(b.r-11)*2)}ctx.restore();ctx.strokeStyle=b.flash>.2?"#ffd36e":"#f8f5ff";ctx.lineWidth=4+b.flash*3;ctx.beginPath();ctx.arc(b.x,b.y,b.r+b.flash*4,0,Math.PI*2);ctx.stroke();ctx.fillStyle="rgba(255,255,255,.72)";ctx.beginPath();ctx.arc(b.x-b.r*.28,b.y-b.r*.3,5,0,Math.PI*2);ctx.fill()}
function drawTargets(){for(let i=0;i<5;i++){const x=205+i*72,y=700+(i%2)*38;ctx.fillStyle=i%2?"#ff72c5":"#69eee0";ctx.shadowBlur=15;ctx.shadowColor=ctx.fillStyle;roundRect(x-20,y-8,40,16,7);ctx.fill()}ctx.shadowBlur=0}
function flipperPoint(cx,cy,a,len){return{x:cx+Math.cos(a)*len,y:cy+Math.sin(a)*len}}
function drawFlipper(cx,cy,a,len,color){const p=flipperPoint(cx,cy,a,len);ctx.strokeStyle="#140a21";ctx.lineWidth=34;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.strokeStyle=color;ctx.lineWidth=24;ctx.shadowBlur=18;ctx.shadowColor=color;ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(cx,cy,11,0,Math.PI*2);ctx.fill()}
function launch(power=.65){if(gameEnded){resetGame();return}if(playBalls.some(o=>o.active))return;power=Math.max(0,Math.min(1,power));started=true;requestTheme("play",!sound);playBalls.splice(1);Object.assign(ball,{active:true,x:SHOOTER_X,y:SHOOTER_REST_Y+power*SHOOTER_PULL_DISTANCE,vx:0,vy:-(520+power*1100),r:13,effectTime:0,trail:[]});inShooterLane=true;plungerPull=0;shake=3+power*2;neonEnergy=.55+power*.3;launchBtn.classList.remove("active");launchBtn.textContent="鋼珠發射中";sfxLaunch(power);showMessage(`蓄力 ${Math.round(power*100)}%・${power<.4?"力道不足會回到發射槽":"鋼珠沿軌道上升"}！`)}
function rearmShooter(){ball.active=false;inShooterLane=false;Object.assign(ball,{x:SHOOTER_X,y:SHOOTER_REST_Y,vx:0,vy:0,trail:[]});launchBtn.classList.remove("active");launchBtn.textContent="按住蓄力";beep(175,.1,.035,"triangle");showMessage("力道不足，鋼珠已回到發射槽，可以再次發射。")}
function sparks(x,y,color,count=12){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=70+Math.random()*170;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,size:2+Math.random()*4,life:.55+Math.random()*.35,color})}if(particles.length>120)particles.splice(0,particles.length-120)}
// 真實機台不會有完全理想的反射角：檯面震動、橡膠與鋼珠接觸點都會帶來
// 一點誤差。每次碰撞後加入約 ±2° 的角度偏移與極小速度差，破壞兩個碰撞面
// 之間的完美週期，避免鋼珠固定在同一路徑上無限互彈。
function loosenBounce(orb,angleRange=.035,speedRange=.022){const speed=Math.hypot(orb.vx,orb.vy);if(speed<1)return;const angle=Math.atan2(orb.vy,orb.vx)+(Math.random()*2-1)*angleRange,multiplier=1+(Math.random()*2-1)*speedRange;orb.vx=Math.cos(angle)*speed*multiplier;orb.vy=Math.sin(angle)*speed*multiplier}
function awardPower(orb){if(powerCooldown>0)return;const roll=Math.random();if(roll<.045&&playBalls.filter(o=>o.active).length<2){const extra=makeBall(orb.x+18,orb.y-10,-orb.vx*.82,orb.vy*.9-90);extra.active=true;playBalls.push(extra);powerCooldown=8;score+=1000;sfxPower();shake=6;neonEnergy=1;showMessage("MULTIBALL！分裂成兩顆鋼珠")}else if(roll<.12){orb.r=Math.random()<.5?9:18;orb.effectTime=3.2;powerCooldown=5;sfxPower();neonEnergy=.85;showMessage(orb.r>13?"能量球變大了！":"高速迷你球！")}}
function collideCircle(c,orb){const dx=orb.x-c.x,dy=orb.y-c.y,d=Math.hypot(dx,dy),min=orb.r+c.r;if(d>=min||d===0)return;const nx=dx/d,ny=dy/d,speed=Math.max(390,Math.hypot(orb.vx,orb.vy)*.98);orb.x=c.x+nx*(min+1);orb.y=c.y+ny*(min+1);orb.vx=nx*speed;orb.vy=ny*speed;loosenBounce(orb,.042,.026);score+=500;paintScore();c.flash=1;shake=Math.max(shake,4.5);neonEnergy=1;sparks(orb.x,orb.y,colors[c.i],15);sfxImpact(c.i);awardPower(orb);const first=!lit.has(c.i);if(first){lit.add(c.i);saveState();paintProgress()}showMessage(`${names[c.i]} +500${first?"・首次點亮！":""}`)}
function collideSegment(ax,ay,bx,by,powered,orb){const abx=bx-ax,aby=by-ay,t=Math.max(0,Math.min(1,((orb.x-ax)*abx+(orb.y-ay)*aby)/(abx*abx+aby*aby))),px=ax+abx*t,py=ay+aby*t,dx=orb.x-px,dy=orb.y-py,d=Math.hypot(dx,dy),min=orb.r+12;if(d>=min||d===0)return;const nx=dx/d,ny=dy/d,dot=orb.vx*nx+orb.vy*ny;if(dot<0||powered){orb.x=px+nx*(min+1);orb.y=py+ny*(min+1);orb.vx-=2*dot*nx;orb.vy-=2*dot*ny;if(powered){orb.vx+=nx*340;orb.vy+=ny*340-260;shake=Math.max(shake,2.5);neonEnergy=Math.max(neonEnergy,.45);sparks(px,py,powered?"#ffd36e":"#69eee0",powered?8:4)}loosenBounce(orb,powered?.032:.024,powered?.022:.014);if(orb.soundWait<=0){beep(powered?330:245,.045,powered?.045:.022,"square");orb.soundWait=.07}}}
function updateOrb(orb,dt){if(!orb.active)return;orb.soundWait=Math.max(0,orb.soundWait-dt);orb.effectTime=Math.max(0,orb.effectTime-dt);if(!orb.effectTime)orb.r+=(13-orb.r)*Math.min(1,dt*7);orb.vy+=520*dt;orb.x+=orb.vx*dt;orb.y+=orb.vy*dt;orb.vx*=Math.pow(.995,dt*60);orb.vy*=Math.pow(.998,dt*60);if(Math.hypot(orb.vx,orb.vy)>180){orb.trail.push({x:orb.x,y:orb.y});if(orb.trail.length>9)orb.trail.shift()}
 if(orb===ball&&inShooterLane){if(orb.x-orb.r<592){orb.x=592+orb.r;orb.vx=Math.abs(orb.vx)*.75}if(orb.x+orb.r>622){orb.x=622-orb.r;orb.vx=-Math.abs(orb.vx)*.75}if(orb.y<155){inShooterLane=false;orb.x=574;orb.y=145;orb.vx=-390;orb.vy=-210;beep(430,.1,.05,"triangle");showMessage("進入主檯面！")}else if(orb.vy>0&&orb.y>=SHOOTER_REST_Y){rearmShooter()}return}
 if(orb.x-orb.r<110){orb.x=110+orb.r;orb.vx=Math.abs(orb.vx)*.82;loosenBounce(orb,.022,.012);if(orb.soundWait<=0){beep(210,.035,.022);orb.soundWait=.08}}if(orb.x+orb.r>585){orb.x=585-orb.r;orb.vx=-Math.abs(orb.vx)*.82;loosenBounce(orb,.022,.012);if(orb.soundWait<=0){beep(210,.035,.022);orb.soundWait=.08}}if(orb.y-orb.r<85){orb.y=85+orb.r;orb.vy=Math.abs(orb.vy)*.8;loosenBounce(orb,.02,.01)}for(const b of bumpers)collideCircle(b,orb);
 collideSegment(118,700,245,842,false,orb);collideSegment(582,700,455,842,false,orb);collideSegment(118,1010,252,872,false,orb);collideSegment(582,1010,448,872,false,orb);
 const la=leftHeld?-.48:.2,ra=rightHeld?Math.PI+.48:Math.PI-.2,lp=flipperPoint(FLIPPER_LEFT_X,FLIPPER_Y,la,FLIPPER_LENGTH),rp=flipperPoint(FLIPPER_RIGHT_X,FLIPPER_Y,ra,FLIPPER_LENGTH);collideSegment(FLIPPER_LEFT_X,FLIPPER_Y,lp.x,lp.y,leftHeld,orb);collideSegment(FLIPPER_RIGHT_X,FLIPPER_Y,rp.x,rp.y,rightHeld,orb);if(orb.y>1060)drainOrb(orb)}
function update(dt){for(const orb of playBalls)updateOrb(orb,dt)}
function drainOrb(orb){orb.active=false;orb.trail=[];if(orb===ball)inShooterLane=false;if(playBalls.some(o=>o.active)){showMessage("多球仍在檯面上！");return}balls--;ballsEl.textContent=balls;sfxDrain();shake=5;if(balls<=0){gameEnded=true;const isBest=score>best;if(isBest){best=score;saveState();bestEl.textContent=pad(best)}gameover.innerHTML=`<div class="card"><div class="newBest">${isBest?"新的最高分":"本局結束"}</div><h2>${score.toLocaleString()}</h2><p>三顆鋼珠都已經回到機台裡。</p><button>再玩一次</button></div>`;gameover.hidden=false;gameover.querySelector("button").onclick=resetGame;launchBtn.textContent="重新開始"}else{playBalls.splice(1);Object.assign(ball,{x:SHOOTER_X,y:SHOOTER_REST_Y,vx:0,vy:0,r:13,effectTime:0});launchBtn.textContent="按住蓄力";showMessage(`還有 ${balls} 顆鋼珠`)}}
function resetGame(){score=0;balls=3;gameEnded=false;gameover.hidden=true;for(const orb of playBalls)orb.active=false;playBalls.splice(1);inShooterLane=false;plungerPull=0;powerCooldown=0;Object.assign(ball,{x:SHOOTER_X,y:SHOOTER_REST_Y,vx:0,vy:0,r:13,effectTime:0,trail:[]});paintScore();ballsEl.textContent=balls;launchBtn.textContent="按住蓄力"}
function pad(n){return String(n).padStart(6,"0")}function paintScore(){scoreEl.textContent=pad(score);if(score>best)bestEl.textContent=pad(score)}function paintProgress(){bestEl.textContent=pad(best);litEl.textContent=lit.size}function showMessage(text){message.textContent=text;message.classList.add("on");messageTimer=1.1}
function hold(button,side,on){if(side==="left")leftHeld=on;else rightHeld=on;button.classList.toggle("active",on);if(on){beep(side==="left"?285:330,.055,.045,"square");shake=Math.max(shake,1.5)}}
for(const [button,side]of[[leftBtn,"left"],[rightBtn,"right"]]){button.addEventListener("pointerdown",e=>{e.preventDefault();button.setPointerCapture(e.pointerId);hold(button,side,true)});button.addEventListener("pointerup",()=>hold(button,side,false));button.addEventListener("pointercancel",()=>hold(button,side,false))}
// 按住就蓄力（跟空白鍵同一條 1.2 秒曲線），往下拉可以拉得更快；取兩者較大。
// 之前只算往下拉的距離：手機上這顆鈕貼在螢幕最底，手指沒地方往下拉，按住放開永遠 0%，球滾回發射槽（2026-09-17 作者回報）。
launchBtn.addEventListener("pointerdown",e=>{if(ball.active)return;e.preventDefault();plungerDragging=true;plungerStartY=e.clientY;plungerPull=0;plungerDragPull=0;plungerHoldStart=performance.now();ball.x=SHOOTER_X;ball.y=SHOOTER_REST_Y;launchBtn.setPointerCapture(e.pointerId);launchBtn.classList.add("active");launchBtn.textContent="蓄力 0%"});
launchBtn.addEventListener("pointermove",e=>{if(!plungerDragging)return;plungerDragPull=Math.max(0,Math.min(1,(e.clientY-plungerStartY)/110))});
function releasePlunger(){if(!plungerDragging)return;plungerDragging=false;plungerHoldStart=0;launch(plungerPull)}launchBtn.addEventListener("pointerup",releasePlunger);launchBtn.addEventListener("pointercancel",releasePlunger);
addEventListener("keydown",e=>{if(e.key==="ArrowLeft"||e.key==="a"){e.preventDefault();hold(leftBtn,"left",true)}if(e.key==="ArrowRight"||e.key==="d"){e.preventDefault();hold(rightBtn,"right",true)}if(e.code==="Space"&&!e.repeat&&!ball.active){e.preventDefault();keyPlungerStart=performance.now();plungerPull=0;launchBtn.classList.add("active");launchBtn.textContent="蓄力 0%"}});addEventListener("keyup",e=>{if(e.key==="ArrowLeft"||e.key==="a")hold(leftBtn,"left",false);if(e.key==="ArrowRight"||e.key==="d")hold(rightBtn,"right",false);if(e.code==="Space"&&keyPlungerStart){e.preventDefault();const power=Math.min(1,(performance.now()-keyPlungerStart)/1200);keyPlungerStart=0;launch(power)}});
function updateEffects(dt){shake=Math.max(0,shake-dt*12);neonEnergy=Math.max(0,neonEnergy-dt*.85);powerCooldown=Math.max(0,powerCooldown-dt);for(const b of bumpers)b.flash=Math.max(0,b.flash-dt*3.4);for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(.94,dt*60);p.vy=p.vy*Math.pow(.94,dt*60)+150*dt;p.life-=dt*1.55;if(p.life<=0)particles.splice(i,1)}}
function frame(now){const dt=Math.min((now-last)/1000,.025);last=now;if(keyPlungerStart&&!ball.active){plungerPull=Math.min(1,(now-keyPlungerStart)/1200);ball.x=SHOOTER_X;ball.y=SHOOTER_REST_Y+plungerPull*SHOOTER_PULL_DISTANCE;launchBtn.textContent=`蓄力 ${Math.round(plungerPull*100)}%`}if(plungerDragging&&plungerHoldStart&&!ball.active){plungerPull=Math.max(plungerDragPull,Math.min(1,(now-plungerHoldStart)/1200));ball.x=SHOOTER_X;ball.y=SHOOTER_REST_Y+plungerPull*SHOOTER_PULL_DISTANCE;launchBtn.textContent=`蓄力 ${Math.round(plungerPull*100)}%`}for(let i=0;i<3;i++)update(dt/3);updateEffects(dt);if(messageTimer>0){messageTimer-=dt;if(messageTimer<=0)message.classList.remove("on")}draw();requestAnimationFrame(frame)}
if(new URLSearchParams(location.search).has("test"))window.__pinballTest={setBall:(x,y,vx,vy)=>{for(const orb of playBalls)orb.active=false;playBalls.splice(1);ball.active=true;inShooterLane=false;Object.assign(ball,{x,y,vx,vy,r:13,effectTime:0,trail:[]})},advance:seconds=>{for(let elapsed=0;elapsed<seconds;elapsed+=.005){update(.005);updateEffects(.005)}},triggerMultiball:()=>{if(playBalls.filter(o=>o.active).length<2){const extra=makeBall(ball.x+20,ball.y-8,-ball.vx*.8,ball.vy-100);extra.active=true;playBalls.push(extra);sfxPower()}},triggerSize:size=>{ball.r=size;ball.effectTime=3},getState:()=>({x:ball.x,y:ball.y,vx:ball.vx,vy:ball.vy,r:ball.r,active:ball.active,inShooterLane,balls,score,activeBalls:playBalls.filter(o=>o.active).length,particles:particles.length})};
paintProgress();paintScore();requestAnimationFrame(frame);
