const $=s=>document.querySelector(s),canvas=$("#game"),ctx=canvas.getContext("2d"),scoreEl=$("#score"),bestEl=$("#best"),ballsEl=$("#balls"),soundBtn=$("#sound"),exitBtn=$("#exit"),launchBtn=$("#launch"),leftBtn=$("#left"),rightBtn=$("#right"),message=$("#message"),gameover=$("#gameover");
const W=700,H=1100,KEY="glitch-park-pinball:v1",THEME="./assets/audio/glitch-park-theme.mp3",embedded=self!==top;const names=["格莉奇","貓草","斑比","諾亞","鐵塔","0x","黑洞先生"],colors=["#9e8ce0","#75b78b","#df91ad","#ce9860","#6c9bc3","#7c8292","#554b62"];
let best=Number(localStorage.getItem(KEY)||0),score=0,balls=3,sound=true,audioContext,themeAudio,last=performance.now(),scale=1,ox=0,oy=0,messageTimer=0,leftHeld=false,rightHeld=false,started=false,gameEnded=false;
const atlas=new Image();atlas.src="./assets/avatar-atlas.webp";atlas.onload=draw;
const ball={x:620,y:970,vx:0,vy:0,r:13,active:false},bumpers=[{x:220,y:300,r:58,i:0},{x:350,y:235,r:58,i:6},{x:480,y:300,r:58,i:1},{x:280,y:445,r:52,i:2},{x:420,y:445,r:52,i:3},{x:350,y:590,r:48,i:4}];
function requestTheme(action,muted=false){if(embedded){parent.postMessage({type:"glitch-park:music",action,track:"theme",url:new URL(THEME,location.href).href,muted},"*");return}themeAudio||=Object.assign(new Audio(THEME),{loop:true,volume:.25});themeAudio.muted=muted;if(action==="play"&&!muted)themeAudio.play().catch(()=>{});if(action==="pause")themeAudio.pause()}
if(embedded){exitBtn.hidden=false;exitBtn.onclick=()=>parent.postMessage({type:"pinball:exit"},"*")}else requestTheme("play");
function beep(freq,dur=.08,vol=.035,type="sine"){if(!sound)return;audioContext||=new(window.AudioContext||window.webkitAudioContext)();const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+dur);o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+dur)}
soundBtn.onclick=()=>{sound=!sound;soundBtn.textContent=`聲音：${sound?"開":"關"}`;soundBtn.setAttribute("aria-pressed",String(!sound));requestTheme("mute",!sound);if(sound){requestTheme("play");beep(660)}};
function resize(){const dpr=Math.min(devicePixelRatio,1.7);canvas.width=innerWidth*dpr;canvas.height=innerHeight*dpr;canvas.style.width=innerWidth+"px";canvas.style.height=innerHeight+"px";scale=Math.min(innerWidth/W,innerHeight/H);ox=(innerWidth-W*scale)/2;oy=(innerHeight-H*scale)/2;ctx.setTransform(dpr,0,0,dpr,0,0);draw()}addEventListener("resize",resize);resize();
function tableTransform(){ctx.setTransform(Math.min(devicePixelRatio,1.7)*scale,0,0,Math.min(devicePixelRatio,1.7)*scale,Math.min(devicePixelRatio,1.7)*ox,Math.min(devicePixelRatio,1.7)*oy)}
function draw(){const dpr=Math.min(devicePixelRatio,1.7);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,innerWidth,innerHeight);const bg=ctx.createRadialGradient(innerWidth/2,innerHeight*.45,20,innerWidth/2,innerHeight*.45,Math.max(innerWidth,innerHeight));bg.addColorStop(0,"#352052");bg.addColorStop(1,"#07030d");ctx.fillStyle=bg;ctx.fillRect(0,0,innerWidth,innerHeight);tableTransform();ctx.save();ctx.shadowBlur=35;ctx.shadowColor="#69eee0";roundRect(70,35,560,1030,34);ctx.fillStyle="#171024";ctx.fill();ctx.strokeStyle="#69eee0";ctx.lineWidth=8;ctx.stroke();ctx.shadowBlur=0;const panel=ctx.createLinearGradient(0,100,0,1000);panel.addColorStop(0,"#3d235c");panel.addColorStop(.55,"#1d1230");panel.addColorStop(1,"#120a20");roundRect(95,65,510,965,25);ctx.fillStyle=panel;ctx.fill();ctx.strokeStyle="#ff72c5";ctx.lineWidth=3;ctx.stroke();drawPoster();drawRails();for(const b of bumpers)drawBumper(b);drawTargets();drawFlipper(275,865,leftHeld?-.48:.2,115,"#69eee0");drawFlipper(425,865,rightHeld?Math.PI+.48:Math.PI-.2,115,"#ff72c5");ctx.fillStyle="#08040e";ctx.beginPath();ctx.moveTo(95,1015);ctx.lineTo(270,870);ctx.lineTo(315,1030);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(605,1015);ctx.lineTo(430,870);ctx.lineTo(385,1030);ctx.closePath();ctx.fill();ctx.strokeStyle="#ffd36e";ctx.lineWidth=5;ctx.strokeRect(587,165,35,825);ctx.fillStyle="#ffd36e";ctx.fillRect(592,995,25,Math.max(8,(970-ball.y)*.12+12));if(ball.active||!gameEnded){ctx.shadowBlur=18;ctx.shadowColor="#fff";ctx.fillStyle="#f7fbff";ctx.beginPath();ctx.arc(ball.x,ball.y,ball.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#b9d8e0";ctx.beginPath();ctx.arc(ball.x-4,ball.y-5,4,0,Math.PI*2);ctx.fill()}ctx.restore()}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function drawPoster(){ctx.save();ctx.globalAlpha=.18;ctx.fillStyle="#9e8ce0";ctx.font="900 78px system-ui";ctx.textAlign="center";ctx.fillText("GLITCH",350,145);ctx.font="700 28px system-ui";ctx.fillStyle="#69eee0";ctx.fillText("NEON PINBALL",350,182);ctx.restore()}
function drawRails(){ctx.strokeStyle="#9cefe8";ctx.lineWidth=10;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(118,190);ctx.lineTo(118,710);ctx.quadraticCurveTo(120,790,205,835);ctx.stroke();ctx.beginPath();ctx.moveTo(582,190);ctx.lineTo(582,710);ctx.quadraticCurveTo(580,790,495,835);ctx.stroke();ctx.strokeStyle="#6c3f88";ctx.lineWidth=5;ctx.beginPath();ctx.arc(350,500,205,.15,Math.PI-.15);ctx.stroke()}
function drawBumper(b){ctx.save();ctx.shadowBlur=22;ctx.shadowColor=colors[b.i];ctx.fillStyle=colors[b.i];ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.beginPath();ctx.arc(b.x,b.y,b.r-10,0,Math.PI*2);ctx.clip();if(atlas.complete&&atlas.naturalWidth){const sw=atlas.naturalWidth/4,sh=atlas.naturalHeight/2;ctx.drawImage(atlas,(b.i%4)*sw,Math.floor(b.i/4)*sh,sw,sh,b.x-b.r+10,b.y-b.r+10,(b.r-10)*2,(b.r-10)*2)}ctx.restore();ctx.strokeStyle="#fff";ctx.lineWidth=4;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.stroke()}
function drawTargets(){for(let i=0;i<5;i++){const x=205+i*72,y=700+(i%2)*38;ctx.fillStyle=i%2?"#ff72c5":"#69eee0";ctx.shadowBlur=15;ctx.shadowColor=ctx.fillStyle;roundRect(x-20,y-8,40,16,7);ctx.fill()}ctx.shadowBlur=0}
function flipperPoint(cx,cy,a,len){return{x:cx+Math.cos(a)*len,y:cy+Math.sin(a)*len}}
function drawFlipper(cx,cy,a,len,color){const p=flipperPoint(cx,cy,a,len);ctx.strokeStyle="#140a21";ctx.lineWidth=34;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.strokeStyle=color;ctx.lineWidth=24;ctx.shadowBlur=18;ctx.shadowColor=color;ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(cx,cy,11,0,Math.PI*2);ctx.fill()}
function launch(){if(gameEnded){resetGame();return}if(ball.active)return;started=true;requestTheme("play",!sound);ball.active=true;ball.x=620;ball.y=965;ball.vx=-85-Math.random()*55;ball.vy=-1040;launchBtn.textContent="鋼珠遊戲中";beep(180,.22,.06,"sawtooth");showMessage("鋼珠發射！")}
function collideCircle(c){const dx=ball.x-c.x,dy=ball.y-c.y,d=Math.hypot(dx,dy),min=ball.r+c.r;if(d>=min||d===0)return;const nx=dx/d,ny=dy/d,speed=Math.max(470,Math.hypot(ball.vx,ball.vy)*1.04);ball.x=c.x+nx*(min+1);ball.y=c.y+ny*(min+1);ball.vx=nx*speed;ball.vy=ny*speed;score+=500;paintScore();beep(520+c.i*45,.07,.045,"triangle");showMessage(`${names[c.i]} +500`)}
function collideSegment(ax,ay,bx,by,powered){const abx=bx-ax,aby=by-ay,t=Math.max(0,Math.min(1,((ball.x-ax)*abx+(ball.y-ay)*aby)/(abx*abx+aby*aby))),px=ax+abx*t,py=ay+aby*t,dx=ball.x-px,dy=ball.y-py,d=Math.hypot(dx,dy),min=ball.r+15;if(d>=min||d===0)return;const nx=dx/d,ny=dy/d,dot=ball.vx*nx+ball.vy*ny;if(dot<0||powered){ball.x=px+nx*(min+1);ball.y=py+ny*(min+1);ball.vx-=2*dot*nx;ball.vy-=2*dot*ny;if(powered){ball.vx+=nx*340;ball.vy+=ny*340-260}beep(260,.05,.035,"square")}}
function update(dt){if(!ball.active)return;ball.vy+=300*dt;ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;ball.vx*=Math.pow(.997,dt*60);ball.vy*=Math.pow(.999,dt*60);if(ball.x-ball.r<110){ball.x=110+ball.r;ball.vx=Math.abs(ball.vx)*.88;beep(210,.035,.02)}if(ball.x+ball.r>625){ball.x=625-ball.r;ball.vx=-Math.abs(ball.vx)*.88;beep(210,.035,.02)}if(ball.y-ball.r<85){ball.y=85+ball.r;ball.vy=Math.abs(ball.vy)*.88}for(const b of bumpers)collideCircle(b);const la=leftHeld?-.48:.2,ra=rightHeld?Math.PI+.48:Math.PI-.2,lp=flipperPoint(275,865,la,115),rp=flipperPoint(425,865,ra,115);collideSegment(275,865,lp.x,lp.y,leftHeld);collideSegment(425,865,rp.x,rp.y,rightHeld);if(ball.y>1060)drain()}
function drain(){ball.active=false;balls--;ballsEl.textContent=balls;beep(105,.35,.05,"sawtooth");if(balls<=0){gameEnded=true;const isBest=score>best;if(isBest){best=score;localStorage.setItem(KEY,String(best));bestEl.textContent=pad(best)}gameover.innerHTML=`<div class="card"><div class="newBest">${isBest?"新的最高分":"本局結束"}</div><h2>${score.toLocaleString()}</h2><p>三顆鋼珠都已經回到機台裡。</p><button>再玩一次</button></div>`;gameover.hidden=false;gameover.querySelector("button").onclick=resetGame;launchBtn.textContent="重新開始"}else{ball.x=620;ball.y=970;ball.vx=ball.vy=0;launchBtn.textContent="發射下一顆";showMessage(`還有 ${balls} 顆鋼珠`)}}
function resetGame(){score=0;balls=3;gameEnded=false;gameover.hidden=true;ball.active=false;ball.x=620;ball.y=970;paintScore();ballsEl.textContent=balls;launchBtn.textContent="發射鋼珠"}
function pad(n){return String(n).padStart(6,"0")}function paintScore(){scoreEl.textContent=pad(score);if(score>best)bestEl.textContent=pad(score)}function showMessage(text){message.textContent=text;message.classList.add("on");messageTimer=1.1}
function hold(button,side,on){if(side==="left")leftHeld=on;else rightHeld=on;button.classList.toggle("active",on);if(on)beep(300,.04,.025,"square")}
for(const [button,side]of[[leftBtn,"left"],[rightBtn,"right"]]){button.addEventListener("pointerdown",e=>{e.preventDefault();button.setPointerCapture(e.pointerId);hold(button,side,true)});button.addEventListener("pointerup",()=>hold(button,side,false));button.addEventListener("pointercancel",()=>hold(button,side,false))}launchBtn.onclick=launch;addEventListener("keydown",e=>{if(e.key==="ArrowLeft"||e.key==="a"){e.preventDefault();hold(leftBtn,"left",true)}if(e.key==="ArrowRight"||e.key==="d"){e.preventDefault();hold(rightBtn,"right",true)}if(e.code==="Space"){e.preventDefault();launch()}});addEventListener("keyup",e=>{if(e.key==="ArrowLeft"||e.key==="a")hold(leftBtn,"left",false);if(e.key==="ArrowRight"||e.key==="d")hold(rightBtn,"right",false)});
function frame(now){const dt=Math.min((now-last)/1000,.025);last=now;update(dt);if(messageTimer>0){messageTimer-=dt;if(messageTimer<=0)message.classList.remove("on")}draw();requestAnimationFrame(frame)}bestEl.textContent=pad(best);paintScore();requestAnimationFrame(frame);
